name: Hello World
on: 
    push:
        branches:
          - master

jobs:
    say-hello-inline-bash:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello World"
